name: tfbindformer
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.11
  - pip

  # CUDA-enabled PyTorch stack
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1

  # Core scientific stack
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - biopython
  - tqdm
  - sentencepiece

  # Training/logging
  - pytorch-lightning
  - torchmetrics

  - pip:
      - transformers
      - wandb